package gopenttd

import "time"

type OpenttdNewgrf struct {
	// Identifier is the NewGRF's ID. This should correspond to its ID on BaNaNaS.
	Identifier string `json:"id"`
	// Hash is the MD5 checksum that the server reports for this NewGRF.
	Hash string `json:"md5"`
}

type OpenttdServerState struct {
	// Status is set to True if the server was parsable, false otherwise.
	Status bool `json:"status"`
	// Error contains any parsing errors.
	Error error `json:"-"`

	// Host is the queried hostname and port combination.
	Host string `json:"host"`
	// Dedicated is set if the server reports itself to be a Dedicated Server (instead of a Listen Server).
	Dedicated bool `json:"dedicated"`
	// Name is the server's advertised Hostname.
	Name string `json:"name"`
	// Version is the server's currently running Version string.
	Version string `json:"version"`
	// NeedPass defines whether the server is private (i.e needs a password)
	NeedPass bool `json:"need-pass"`

	// Language is the given Server Language.
	// If you need the string version of a language, use
	// gopenttd.GetISOLanguage(OpenttdServerState.Language) or gopenttd.GetLanguage(OpenttdServerState.Language)
	Language int `json:"language"`

	// Environment is the environment identifier.
	// If you need the string version of the environment, use
	// gopenttd.GetEnvironment(OpenttdServerState.Environment)
	Environment int `json:"environment"`

	// Map is the name of the map currently running. Note that this will be set to "Random Map" if the map was generated by a seed.
	Map string `json:"map_name"`

	// MapHeight and MapWidth are the height and width of the current map in tiles.
	MapHeight uint16 `json:"map_height"`
	MapWidth  uint16 `json:"map_width"`

	// DateStart and DateCurrent are time objects relating to the start of the game and the current date.
	DateStart   time.Time `json:"date_start"`
	DateCurrent time.Time `json:"date_current"`

	// The following should be self explanatory.
	NumClients    int `json:"clients_active"`
	MaxClients    int `json:"clients_max"`
	NumSpectators int `json:"spectators_active"`
	MaxSpectators int `json:"spectators_max"`
	NumCompanies  int `json:"companies_active"`
	MaxCompanies  int `json:"companies_max"`

	// NewgrfCount is the number of currently active newgrfs.
	NewgrfCount int `json:"newgrf_count"`
	// NewgrfActive is a set of OpenttdNewgrf structs corresponding to the currently active Newgrfs.
	NewgrfActive []OpenttdNewgrf `json:"newgrf_active"`
}
